name: Local Config
version: 1.0.0
schema: v1
models:
  - name: llama3.1:8b
    provider: ollama
    model: llama3.1:8b
    roles:
      - chat
      - edit
      - apply
      - autocomplete
      - embed
  - name: qwen2.5-coder:14b
    provider: ollama
    model: qwen2.5-coder:14b
    roles:
      - chat
      - edit
      - apply
      - autocomplete
      - embed
  - name: qwen2.5-coder:7b
    provider: ollama
    model: qwen2.5-coder:7b
    roles:
      - chat
      - edit
      - apply
      - autocomplete
      - embed
  - name: gemma2:9b
    provider: ollama
    model: gemma2:9b
    roles:
      - chat
      - edit
      - apply
      - autocomplete
      - embed
  - name: gemma3:12b
    provider: ollama
    model: gemma3:12b
    roles:
      - chat
      - edit
      - apply
      - autocomplete
      - embed
