version: '3'
services:
    postgres:
        image: postgres:latest
        container_name: postgres
        environment:
            POSTGRES_PASSWORD: password
        env_file: .env
        ports:
            - "5432:5432"
        volumes:
            - pg-data:/var/lib/postgresql/data
        networks:
          - network
    SERVICE_2:
        image: IMAGE_NAME:VERSION
        ports: 
            - EXTERNAL_PORT:INTERNAL_PORT
        networks:
          - network
    app:
        build: .
        env_file: .env
        ports: 
            - EXTERNAL_PORT:INTERNAL_PORT
        networks:
            - network
        volumes:
            - ./files:/usr/app/files
    
volumes:
    pg-data:
        driver: local

networks:
    network:
