#!/usr/bin/env bash
# Description: Wrapper for psql executing inside PostgreSQL Docker container
set -euo pipefail
SCRIPT_DIR="$(cd -P "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
exec "${SCRIPT_DIR}/pg-docker-cli" "psql" "$@"
