services:
  conduit:
    image: ghcr.io/psiphon-inc/conduit/cli:latest
    container_name: conduit
    restart: unless-stopped
    network_mode: host
    user: "1000:1000"
    command: start --max-common-clients 150 --bandwidth 10 --data-dir /app/data --metrics-addr 127.0.0.1:9090
    # This is the magic label that invites Watchtower in to update this container
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    volumes:
      - ./data:/app/data

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    network_mode: host # On the host network alongside Conduit
    user: "1000:1000"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.listen-address=:9091' # Forces Prometheus to use 9091 to avoid clashing with Conduit
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus_data:/prometheus

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    # Move the bridge access here so Grafana can reach the newly hosted Prometheus
    # Grafana will see Prometheus at http://host.docker.internal:9091
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "127.0.0.1:3030:3000"
    user: "1000:1000"
    # This is the magic label that invites Watchtower in to update this container
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    volumes:
      - ./grafana_data:/var/lib/grafana
      - ./grafana-provisioning/dashboards/default.yaml:/etc/grafana/provisioning/dashboards/default.yaml:ro
      - ./grafana-provisioning/dashboards:/var/lib/grafana/dashboards:ro
      - ./grafana-provisioning/datasources:/etc/grafana/provisioning/datasources:ro
