#!/usr/bin/env bash
# Description: Wrapper for bcp executing inside Microsoft SQL Server Docker container

SCRIPT_SOURCE="$(readlink -f "${BASH_SOURCE[0]}")"
SCRIPT_DIR="$(cd -P "$(dirname "$SCRIPT_SOURCE")" && pwd)"
exec "${SCRIPT_DIR}/sql-docker-cli" "bcp" "$@"
