# Redis Server Configuration
# Mounted into /usr/local/etc/redis/redis.conf

# Network & Connectivity
bind 0.0.0.0
protected-mode no
port 6379
tcp-backlog 511
timeout 0
tcp-keepalive 300

# General & Process Management
daemonize no
supervised no
loglevel notice
logfile /var/log/redis/redis.log

# Persistence (Snapshotting RDB)
dir /data
dbfilename dump.rdb
save 3600 1 300 100 60 10000
stop-writes-on-bgsave-error yes
rdbcompression yes
rdbchecksum yes

# Persistence (Append Only File AOF)
appendonly yes
appendfilename "appendonly.aof"
appenddirname "appendonlydir"
appendfsync everysec
no-appendfsync-on-rewrite no
auto-aof-rewrite-percentage 100
auto-aof-rewrite-min-size 64mb

# Memory Management
maxmemory-policy noeviction

# Authentication (optional)
${REDIS_REQUIREPASS}
